# fly.toml app configuration file generated for apamsa-website-server on 2023-08-09T22:07:23-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "apamsa-website-server"
primary_region = "bos"

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
